### ISSUE TITLE
Нужна переменная

### ISSUE THREAD

**Issue by bonvech** [Beskarteo/Pole-chudes#1]
Текст

`Попрубуйте ввести заново. Напоминаем вам нужно ввести одну маленькую букву русского алфавита, которую вы еще не вводили е = ё. Или угадать слово. Введите #сдаться чтобы сдаться. И #help чтобы узнать правтла и команды.
`
повторяется в программе много раз. Его лучше вынести в строковую переменную и выводить на экран там, где нужно. Кстати, и ошибки в этом тексте придется исправлять только один раз.

**Comment by Beskarteo** [comment]
я сделал переменные zanovo и napom
